/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.Arrays;


class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test
   public void EndBiggerThanStart() {
      ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1, 2, 3, 4));
      System.out.println(App.SubArrSummation(array, 3,2));
      assertTrue(App.SubArrSummation(array, 3,2)==-1);
    }

    @Test
    public void SampleExpectedCase() {
      ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1, 2, 3, 4,5,6,7));
      assertTrue(App.SubArrSummation(array,3,6)==15);
    }
    @Test
    public void SampleExpectedCase2() {
      ArrayList<Integer> array = new ArrayList<>(Arrays.asList(89, 77, 46, 31,90,65,444));
      assertTrue(App.SubArrSummation(array,0,2)==166);
    }
    @Test
    public void StartAndEndEqual() {
      ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1, 2, 3, 4,5,6,7));
      assertTrue(App.SubArrSummation(array, 1,1)==-1);
    }
    @Test
    public void EndBiggerThanSize() {
      ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1, 2, 3, 4,5,6,7));
      assertTrue(App.SubArrSummation(array, 1,10)==-1);
    }

    @Test
    public void NullArray() {
      assertTrue(App.SubArrSummation(null, 1,5)==-1);
    }

}

